puts "The students of March 2015 cohort at Makers Academy"
puts "--------------"
puts "Andrea Armiliato"
puts "Caron Stace"
puts "Maciej Kurek"
puts "Paul Wallis"
puts "Guillaume Bouffard"
puts "George McGowan"
puts "Sarah O'Connor"
puts "Richard Lynch"
puts "Max Weaver"
puts "Phoebe Hugh"
puts "Sanjay Purswani"